version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  ignore:
    # Ignore all dependencies that (currently) point to GitHub forks that we ourselves maintain
    #   (in order for updates to be available, we ourselves would need to trigger a fork sync.)
    - dependency-name: time_will_tell
    - dependency-name: iso
    - dependency-name: selectize-rails
    - dependency-name: i18n-country-translations
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  ignore:
    # Version 7 automatically activates React Compiler strict rules that we won't implement in the old ecosystem
    - dependency-name: eslint-plugin-react-hooks
      versions:
        - ">= 7"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/next-frontend"
  schedule:
    interval: weekly
  groups:
    react:
      patterns:
        - "react"
        - "react-dom"
    payload:
      patterns:
        - "payload"
        - "@payloadcms/*"
    chakra-ui:
      patterns:
        - "@chakra-ui/*"
    fullcalendar:
      patterns:
        - "@fullcalendar/*"
    nextjs:
      patterns:
        - "next"
        - "eslint-config-next"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
