dist: trusty
sudo: false
language: ruby
rvm:
  - 2.4.1
bundler_args: --path $HOME/.bundle
cache:
  directories:
    - $HOME/.phantomjs
    - $HOME/.bundle
    - WcaOnRails/node_modules
  yarn: true
env:
  global:
    - DATABASE_URL=mysql2://root:@127.0.0.1:3306/wca_test
    - RACK_ENV=test
before_install:
  # TMP BEGIN (see: https://github.com/thewca/worldcubeassociation.org/issues/1656)
  - gem uninstall -i /home/travis/.rvm/gems/ruby-2.4.1@global -x bundler
  - gem install -i /home/travis/.rvm/gems/ruby-2.4.1@global -v 1.14.6 bundler
  # TMP END
  - nvm install 6.9.1
  - nvm use 6.9.1

  # From https://yarnpkg.com/en/docs/install-ci#travis-tab
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

  - cd WcaOnRails/
before_script:
  - echo "***** Some debugging info for https://github.com/thewca/worldcubeassociation.org/issues/1629 ****"
  - mysql -e 'select host, user, password from mysql.user;'
  - ps -efw | grep -i mysql
  - service --status-all
  - date
  - dmesg | grep -i -C 100 mysql || true
  - ps -efw | grep -i mysql

  - bundle exec rake db:reset
  - bundle exec rake assets:precompile
  - bin/webpack-dev-server &
script:
  - bundle exec pre-commit run git
  - bundle exec rubocop
  - bundle exec rake
