development:
  adapter: redis
  url: <%= EnvConfig.ACTIONCABLE_REDIS_URL %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= EnvConfig.ACTIONCABLE_REDIS_URL %>
  channel_prefix: wca_production
